### PR TITLE
Optimizing a little

### PR DESCRIPTION
**Pull request by jlesceau**
Removed glutton for-in loops and useless function calls
Tried to transform recursives functions (_scan & isValid) into iterative functions but it made no difference.

About 15% gain with check() and 25% with isValid() : 
 - 1400ms instead of 1650ms for 20000 calls of check()
 - 1400ms instead of 1850ms for 50000 calls of isValid()

Use custom type does'nt change anything

### CODE REVIEW

**Comment by jlesceau** [comment]
In a case the type isn't valid or the data don't match the type, we want the scanning function to check a small number of values before getting to the error. Wouldn't be interesting to scan first all scalar types and then go through deep objects or arrays ?
It could also result in a loss of perfs when sorting the keys, especially when the type is correct..

**Comment by jlesceau** [comment]
New way to test if exclusive or optionnal ( charAt is much faster than match ).
Skip the 'unexpected key' test in a object when the expected types are here and the number of keys is the same.
New way to test if a object has a given key ( http://jsperf.com/hasownproperty-vs-in-vs-undefined/12 )

**Comment by jlesceau** [comment]
| Test check() | Modified | Original |
| :------------- | :-------------: | :-------------: |
| Deep object |||
| noError | 1664ms | 1583ms |
| errorBeginning | 152ms | 1104ms |
| errorEnd | 1561ms | 2917ms |
| unexpectedKey |  1683ms | 2430ms |
| ---- | ---- | ---- |
| Large object of strings |||
| noError | 2118ms | 4922ms |
| errorBeginning | 190ms | 1171ms |
| errorEnd | 2086ms | 5969ms |
| unexpectedKey | 2180ms | 6013ms |
| ---- | ---- | ---- |
| Large object of functions |||
| noError | 2383ms | 5124ms |
| errorBeginning | 188ms | 1187ms |
| errorEnd | 2269ms | 6253ms |
| unexpectedKey | 2389ms | 6032ms |
| ---- | ---- | ---- |
| Array of strings |||
| noError | 2104ms | 4498ms |
| errorBeginning | 114ms | 1098ms |
| errorEnd | 2188ms | 5627ms |
| ---- | ---- | ---- |
| Array of customs |||
| noError | 151ms | 1750ms |
| errorBeginning | 258ms | 2083ms |
| errorEnd | 138ms | 1755ms |

**Comment by jlesceau** [comment]
| Test isValid() | Modified | Original |
| :---- | :----: | :----: |
| Deep object |||
| noError | 960ms | 1073ms |
| errorBeginning | 123ms | 126ms |
| errorEnd | 946ms | 1039ms |
| ---- | ---- | ---- |
| Large object of strings |||
| noError | 2119ms | 3287ms |
| errorBeginning | 159ms | 197ms |
| errorEnd | 2088ms | 3201ms |
| ---- | ---- | ---- |
| Large object of functions |||
| noError | 2086ms | 2998ms |
| errorBeginning | 164ms | 189ms |
| errorEnd | 2038ms | 3731ms |
| ---- | ---- | ---- |
| Array of strings |||
| noError | 89ms | 210ms |
| error | 109ms | 238ms |
| ---- | ---- | ---- |
| Array of customs|||
| noError | 95ms | 141ms |

**Comment by jacomyal** [comment]
Here are some notes about the object returned by `_scan` when the value matches the type:
  - I don't like the `"optional"`key. Maybe `"nully"` might be more appropriate?
  - I think the `"type"` of the value should be returned as well.

**Comment by jacomyal** [comment]
More precisely, here are some notes that might make `_scan` more consistent:
  - It always returns an object, with the keys **type**, **expected** and **value**.
  - If the type does not match, then the error message is returned under the key **error**.
  - If the type is `undefined` or `null` and the `?` operator was used, then the **nully** flag has the value `true`.

What do you think about that?

**Comment by jlesceau** [comment]
| Test isValid() | Modified | Original | Ratio |
| :------------- | :-------------: | :-------------: | :-------------: |
| **Deep object** ||||
| noError | 922ms | 975ms | -0.05 |
| errorBeginning | 114ms | 114ms | 0 |
| errorEnd | 912ms | 979ms | -0.07 |
| **Large object of strings** ||||
| noError | 1909ms | 2542ms | -0.25 |
| errorBeginning | 160ms | 176ms | -0.09 |
| errorEnd | 1946ms | 2793ms | -0.3 |
| **Large object of functions** ||||
| noError | 1946ms | 2546ms | -0.24 |
| errorBeginning | 157ms | 173ms | -0.09 |
| errorEnd | 1840ms | 2468ms | -0.25 |
| **Array of strings** ||||
| noError | 83ms | 120ms | -0.31 |
| error | 102ms | 128ms | -0.2 |
| **Array of customs** ||||
| noError | 92ms | 127ms | -0.28 |

**Comment by jlesceau** [comment]
| Test check() | Modified | Original | Ratio |
| :------------- | :-------------: | :-------------: | :-------------: |
| **Deep object** ||||
| noError | 1647ms | 1573ms | +0.05 |
| errorBeginning | 145ms | 1054ms | -0.86 |
| errorEnd | 1650ms | 2822ms | -0.42 |
| unexpectedKey | 1720ms | 2329ms | -0.26 |
| **Large object of strings** ||||
| noError | 2344ms | 4756ms | -0.51 |
| errorBeginning | 201ms | 1139ms | -0.82 |
| errorEnd | 2275ms | 5871ms | -0.61 |
| unexpectedKey | 2336ms | 5789ms | -0.6 |
| **Large object of functions** ||||
| noError | 2397ms | 4968ms | -0.52 |
| errorBeginning | 204ms | 1138ms | -0.82 |
| errorEnd | 2163ms | 5790ms | -0.63 |
| unexpectedKey | 2246ms | 5794ms | -0.61 |
| **Array of strings** ||||
| noError | 2028ms | 4379ms | -0.54 |
| errorBeginning | 116ms | 1092ms | -0.89 |
| errorEnd | 2176ms | 5487ms | -0.6 |
| **Array of customs** ||||
| noError | 9167ms | 14600ms | -0.37 |
| errorBeginning | 302ms | 1987ms | -0.85 |
| errorEnd | 9321ms | 16219ms | -0.43 |

**Comment by jlesceau** [comment]
| Test check() | Modified | Original | Ratio |
| :------------- | :-------------: | :-------------: | :-------------: |
| **Deep object** ||||
| noError | 1763ms | 1595ms | +0.11 |
| errorBeginning | 145ms | 1060ms | -0.86 |
| errorEnd | 1551ms | 2832ms | -0.45 |
| unexpectedKey | 1672ms | 2362ms | -0.29 |
| **Large object of strings** ||||
| noError | 2275ms | 4641ms | -0.51 |
| errorBeginning | 195ms | 1121ms | -0.83 |
| errorEnd | 2230ms | 5794ms | -0.62 |
| unexpectedKey | 2352ms | 5818ms | -0.6 |
| **Large object of functions** ||||
| noError | 2455ms | 5044ms | -0.51 |
| errorBeginning | 202ms | 1151ms | -0.82 |
| errorEnd | 2235ms | 6410ms | -0.65 |
| unexpectedKey | 2343ms | 5971ms | -0.61 |
| **Array of strings** ||||
| noError | 2099ms | 4521ms | -0.54 |
| errorBeginning | 116ms | 1130ms | -0.9 |
| errorEnd | 2187ms | 5726ms | -0.62 |
| **Array of customs** ||||
| noError | 9051ms | 14633ms | -0.38 |
| errorBeginning | 253ms | 2051ms | -0.88 |
| errorEnd | 9060ms | 16733ms | -0.46 |

**Pull request merged**
